listener 1883
allow_anonymous false
password_file /mosquitto/config/passwd
acl_file /mosquitto/config/aclfile

# Listener MQTTS para telemetría cifrada.
listener 8883
cafile /mosquitto/certs/broker/ca.crt
certfile /mosquitto/certs/broker/broker.crt
keyfile /mosquitto/certs/broker/broker.key
require_certificate false

persistence true
persistence_location /mosquitto/data/

log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
