FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN python -m pip install --no-cache-dir --require-hashes -r requirements.txt

COPY run_mqtt.py .
COPY api_avicola/ ./api_avicola/

CMD ["python", "run_mqtt.py"]
